### ISSUE TITLE
bloom 0.5.1 still generates invalid pull reuqests

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/bloom#252]
https://github.com/ros/rosdistro/pull/3293
https://github.com/ros/rosdistro/pull/3356

**Comment by wjwwood** [comment]
I've made some changes in `0.5.20` which should resolve this (hopefully). I'll come back and reopen this in a few days if we see it anymore.

**Comment by dirk-thomas** [comment]
While much less common this is still happening with the current version 0.5.20: https://github.com/ros/rosdistro/pull/9930/
